
# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.1.2
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3  
#  aws-cli: circleci/aws-cli@2.0.6
jobs:
  make-doc:
    docker:
      - image: circleci/python:3.9-buster
    steps:
      - setup_remote_docker:
          version: 20.10.14    
      - run: sudo apt-get update
      - checkout
      - run: pip install --user sphinx sphinx_rtd_theme autodocsumm
      - run:
          name: Build doc
          command: |
            cd doc
            make html

  build-push-image:
    docker:
      - image: circleci/python:3.9-buster
    steps:      
      - setup_remote_docker:
          version: 20.10.14 
      - aws-ecr/build-and-push-image:   
          aws-cli-version: latest
          executor: aws-ecr/default
          new-profile-name: 
          create-repo: true
          extra-build-args: '--compress'
          region: ap-northeast-1
          path: doc
          platform: linux/amd64
          public-registry: false
          push-image: true
          repo: ecr-shankar-tool-box/demo-app
          repo-scan-on-push: true
          skip-when-tags-exist: false
          tag: 'latest'    

  create-deployment:
    docker:
      - image: 'cimg/python:3.10'
    parameters:
      cluster-name:
        description: |
          Cluster Name
        type: string
      aws-region:
        description: |
          AWS Region
        type: string        
    steps:
      - run:
          name: Build doc
          command: |
            git clone https://github.com/shankarcit/eks-deploy.git ~/deployment/configs/
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          aws-region: << parameters.aws-region >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: ~/deployment/configs/deployment/demo-app-deployment.yaml
          resource-name: deployment/demoapp-deployment

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-artifact:
    jobs:
      - make-doc
      - build-push-image:
          requires:
            - make-doc      
      - create-deployment:
          requires:
            - build-push-image       
          cluster-name: shan-tempdev-k8s-09101237
          aws-region: ap-northeast-1
